package-lock.json
package.json
server.ts
src/controller/locationController.ts
src/database/migrations/20250610065223-create-states-table.js
src/database/migrations/20250610065231-create-cities-table.js
src/database/migrations/20250610065241-create-districts-table.js
src/database/models/city.ts
src/database/models/district.ts
src/database/models/state.ts
src/routes/locationRoutes.ts
src/scripts/importLocations.ts

Created database tables: states, cities, and districts.
Defined associations/relationships between states, cities, and districts.
Implemented a script to seed location data (state → city → district) from a CSV file.
Created APIs to list(along with pagination and searching):
All states
Cities by state
Districts by city
Applied basic validations and ordering for consistent response.
Verified seeded data and API responses for sample locations.

feat: Add state, city, district tables with seed script and listing APIs

---

server.ts
src/controller/adminController/coldStorage/operationalChallengeController.ts
src/controller/adminController/coldStorage/storageTypeController.ts
src/controller/adminController/coldStorage/usageTypeController.ts
src/database/migrations/20250612124505-admin-storage-types.js
src/database/migrations/20250612124854-admin-usage-types.js
src/database/migrations/20250612125111-admin-operational-challenge.js
src/database/models/adminModels/coldStorage/adminOperationalChallenge.ts
src/database/models/adminModels/coldStorage/adminStorageType.ts
src/database/models/adminModels/coldStorage/adminUsageType.ts
src/routes/adminRoutes/coldStorage/adminOperationalChallengeRoutes.ts
src/routes/adminRoutes/coldStorage/adminStorageTypeRoutes.ts
src/routes/adminRoutes/coldStorage/adminUsageTypeRoutes.ts
src/validation/adminValidation.ts

CRUD apis for storage types , usage types , operational challenges.

feat: admin cold storage management

---

server.ts
src/controller/traderController.ts
src/routes/traderRoutes.ts
src/services/traderService.ts
src/validation/traderValidation.ts

Implement trader onboard API with joi validations
Add get profile overview API

Implement trader onboard  and get profile overview APIs

---

src/controller/user.ts
src/database/models/agent.ts

Refactored agent login api code and modify token expiration time

Refactored agent login code and modify token expiration time

---

src/routes/userRoutes.ts
src/services/userServices.ts

allow all authenticated users to access user profile api

fix: allow all auth users to access user profile api

---

src/controller/user.ts
src/database/migrations/20250620073936-add-security-fields-to-users.js
src/database/models/agent.ts
src/database/models/user.ts
src/services/userServices.ts

Migrate security info fields (lastLogin, passwordUpdatedAt) to users table for agent profiles
Add security information and onboarding stats in agent profile API

Add security information and onboarding stats for agent profile

---

src/database/migrations/20250527192210-create-farmer-and-sub-tables.js

Add fields in land detail migration file

fix: Add fields in land detail migration file

---

src/scripts/importLocations.ts

Optimize and simplify location seed import script for staging env

refactor: Optimize and simplify location seed import script

---

src/controller/locationController.ts
src/database/migrations/20250625062923-add-stateId-to-districts.js
src/database/models/district.ts
src/scripts/importLocations.ts

Implement district changes
Modify import location script
Remove pagination and searching from related listing apis

Implement district changes and remove searching from related apis

---

src/controller/coldStorage.ts
src/controller/farmer.ts
src/controller/traderController.ts
src/routes/coldStorageRoutes.ts
src/routes/farmerRoutes.ts
src/routes/traderRoutes.ts

1. self onboard for farmer, cold storage and trader.

feat: self registrations implemented

---

src/controller/adminController/farmer/potatoTypeController.ts
src/controller/farmer.ts
src/database/migrations/20250702125703-add-land-details-fields.js
src/database/migrations/20250702132931-add-farmer-related-tables.js
src/database/models/adminModels/farmer/adminPotatoType.ts
src/database/models/landDetails.ts
src/database/models/potatoType.ts
src/routes/adminRoutes/farmer/adminPotatoTypeRoutes.ts
src/services/farmerServices.ts
src/validation/adminValidation.ts
src/validation/farmerValidation.ts

Added new fields in farmer land details table
Added potato type schema and CRUD APIs 
Modify farmer onboard and overview API

farmer land details and related modules changes

---

server.ts
src/controller/adminController/trader/marketCoverageController.ts
src/database/migrations/20250703103033-add-trader-fields.js
src/database/migrations/20250703103404-add-market-covered-table.js
src/database/models/adminModels/trader/adminMarketCoverage.ts
src/database/models/trader/marketCoverage.ts
src/database/models/trader/trader.ts
src/routes/adminRoutes/trader/adminMarketCoverageRoutes.ts
src/services/farmerServices.ts
src/services/traderService.ts
src/validation/adminTraderValidation.ts
src/validation/farmerValidation.ts
src/validation/traderValidation.ts

Modify trader fields
Create market coverage schema
Modify trader onbaord api

Modify trader, its related modules and onboard API of trader

---

src/controller/farmer.ts
src/controller/traderController.ts
src/database/models/trader/trader.ts
src/routes/farmerRoutes.ts
src/routes/traderRoutes.ts
src/services/farmerServices.ts
src/services/traderService.ts
src/validation/farmerValidation.ts
src/validation/traderValidation.ts

Implement farmer and trader update APIs
Add role based check for update APIs

Implement farmer and trader update APIs 

---

src/controller/coldStorage.ts
src/routes/coldStorageRoutes.ts
src/services/coldStorageService.ts
src/validation/coldStorageValidation.ts

Implement cold storage update API with role based checks

Implement cold storage update API with role based checks

---

src/routes/adminRoutes/farmer/adminBrandPreferenceReasonRoutes.ts
src/routes/adminRoutes/farmer/adminSeedBrandRoutes.ts
src/routes/adminRoutes/farmer/adminSellingChannelRoutes.ts
src/routes/adminRoutes/farmer/adminSellingPlaceRoutes.ts
src/routes/adminRoutes/farmer/adminSellingPriceRoutes.ts
src/routes/adminRoutes/trader/adminCropTradedRoutes.ts
src/routes/adminRoutes/trader/adminMarketCoverageRoutes.ts
src/routes/adminRoutes/trader/adminTraderInterestRoutes.ts
src/routes/adminRoutes/trader/adminTraderTypeRoutes.ts
src/routes/adminRoutes/trader/adminTraderVarietyRoutes.ts

Made active records listing routes public

Made active records listing routes public

---

src/database/migrations/20250709083158-add-pinCode-in-farmers.js
src/database/models/farmer.ts
src/services/farmerServices.ts
src/validation/farmerValidation.ts

Add pinCode for farmer

---

src/scripts/seed.ts
src/utils/constants/farmerSeedList.ts

Add seed data for farmer modules

Add seed data for farmer modules

---

src/routes/userRoutes.ts
src/services/userServices.ts

Modify admin dashboard API and its request type

Modify admin dashboard api and its request type

---

src/services/traderService.ts

added search on onboardedBy user's name and trader's email.

fix: added search on name of onboardedBy and trader email

---

src/database/migrations/20250715110621-add-state-in-agent.js
src/database/models/agent.ts
src/services/agentService.ts
src/services/userServices.ts
src/validation/agentValidation.ts
src/validation/userValidator.ts

Add state in agent and api changes accordingly

Add state in agent and api changes accordingly

---

src/validation/agentValidation.ts

modify joi update agent schema

modify joi update agent schema

---

src/controller/user.ts
src/services/agentService.ts
src/services/userServices.ts

Add duplicate email and phone validation for agent APIs
Agent login fixes based on its status

fix: Add duplicate email and phone validation for agent apis and login fixes

---

src/controller/user.ts

Modify agent login response

---

src/controller/agent.ts
src/services/agentService.ts
src/utils/getMonthWiseRegistration.ts

agent performance for selected year through query , listing all 12 months

fix: agent performance for selected year

---

src/controller/agent.ts
src/controller/user.ts
src/routes/userRoutes.ts
src/services/agentService.ts
src/services/userServices.ts

1.  giving registration type of user in verify otp .
2. get api to retreive registration types of user.

feat: retrieve registration type of user

---

src/controller/user.ts
src/routes/userRoutes.ts
src/services/userServices.ts

Implement recent registrations api for admin

Implement recent registrations api for admin

---

src/controller/traderController.ts
src/database/models/coldStorage.ts
src/database/models/farmer.ts
src/services/coldStorageService.ts
src/services/farmerServices.ts
src/services/traderService.ts

1.  added onboard by  details in profile apis of all three.
2. added filters in trader.
3. added state filter in all .

feat: added filters in trader listing

---

src/database/migrations/20250721070242-add-district-in-mandi-details.js
src/database/models/trader/mandiDetail.ts
src/validation/traderValidation.ts

Add district in trader mandi details

Add district in trader mandi details

---

src/controller/agent.ts
src/database/migrations/20250722074428-create-help-and-support-table.js
src/database/models/helpAndSupport.ts
src/routes/agentRoutes.ts
src/services/agentService.ts
src/validation/userValidator.ts

1. model and migration for helpAndSupport.
2. crud apis for support ticket request and admin action.
3. status update.

feat: help and support ticket implemented

---

src/controller/coldStorage.ts
src/controller/farmer.ts
src/controller/traderController.ts
src/database/migrations/20250722103119-add-isDeleted-to-farmers.js
src/database/migrations/20250722103128-add-isDeleted-to-cold-storages.js
src/database/migrations/20250722103134-add-isDeleted-to-traders.js
src/database/models/coldStorage.ts
src/database/models/farmer.ts
src/database/models/trader/trader.ts
src/routes/coldStorageRoutes.ts
src/routes/farmerRoutes.ts
src/routes/traderRoutes.ts
src/services/coldStorageService.ts
src/services/farmerServices.ts
src/services/traderService.ts

Implement soft deletion apis for farmer, cold storage and trader

Implement soft deletion for farmer, cold storage and trader

---

package-lock.json
package.json
src/controller/coldStorage.ts
src/controller/farmer.ts
src/controller/traderController.ts
src/database/models/chamberCapacity.ts
src/database/models/coldStorageType.ts
src/database/models/constructionType.ts
src/database/models/dryingFacilityDetail.ts
src/database/models/elevatorAndStuffing.ts
src/database/models/farmer.ts
src/database/models/featureOfStorage.ts
src/database/models/landDetails.ts
src/database/models/monitoringFacility.ts
src/database/models/operationalChallenge.ts
src/database/models/otherFacility.ts
src/database/models/potatoDisposalSystem.ts
src/database/models/powerFacility.ts
src/database/models/roofType.ts
src/database/models/seasonWiseStorageSystem.ts
src/database/models/shed.ts
src/database/models/slabWiseDiscount.ts
src/database/models/storageBookingSystem.ts
src/database/models/usageType.ts
src/routes/coldStorageRoutes.ts
src/routes/farmerRoutes.ts
src/routes/traderRoutes.ts
src/services/coldStorageService.ts
src/services/farmerServices.ts
src/services/traderService.ts

Implement export data APIs for farmer, cold storage, and trader

feat: Implement export data functionality for farmer, cold storage, and trader

---

src/services/coldStorageService.ts
src/services/farmerServices.ts

Add on boarded by info in farmer and cold storage listing

Add on boarded by info in farmer and cold storage listing

---

src/database/models/otherCropGrown.ts
src/validation/farmerValidation.ts

Made crop name optional in other crops grown

Made crop name optional in other crops grown

---

src/database/migrations/20250731073010-add-other-field-to-potatoVarietyGrown.js
src/database/models/potatoVarietyGrown.ts
src/services/farmerServices.ts
src/validation/farmerValidation.ts

isCustom field for helping frontend for prefilling potato Variety grown

feat: added isCustom field for potatoVarietyGrown

---

src/services/coldStorageService.ts
src/services/farmerServices.ts
src/services/traderService.ts

1. searching based on mobile in farmer.
2. onboardedByUser filter : self , admin , agent  for all users.

fix: modified filters in all users

---

src/controller/user.ts

Modify response status for verify otp api

Modify response status for verify otp api

---

src/database/migrations/20250812081651-create-seed-brand-table.js
src/database/models/seedBrandName.ts
src/database/models/user.ts
src/services/coldStorageService.ts
src/services/farmerServices.ts
src/services/traderService.ts
src/services/userServices.ts
src/validation/coldStorageValidation.ts
src/validation/farmerValidation.ts
src/validation/traderValidation.ts

1. valdation changes in all users.
2.  seed brand name now takes multiple values.

fix: validation changes acc. to doc

---

server.ts
src/controller/subAdminController.ts
src/controller/user.ts
src/database/migrations/20250812074652-add-user-field.js
src/database/migrations/20250812081818-add-isActive-to-users.js
src/database/migrations/20250812103155-create-sub-admin-permissions.js
src/database/models/subAdminPermission.ts
src/database/models/user.ts
src/routes/subAdminRoutes.ts
src/services/subAdminService.ts
src/services/userServices.ts
src/utils/constants/permissions.ts
src/utils/userAuth.ts
src/validation/subAdminValidation.ts
src/validation/userValidator.ts

- Added Super Admin role
- Maintained onboarded status for mobile app users
- Implemented CRUD APIs for sub-admins
- Handled RBAC and permissions for sub-admins

feat: Implement sub admin CRUD apis with permission and maintain mob app onboarded status

---

src/controller/agent.ts
src/database/migrations/20250818074622-create-agent-monthly-target-table.js
src/database/models/agentMonthlyTarget.ts
src/routes/agentRoutes.ts
src/services/agentService.ts
src/validation/agentValidation.ts

1.  Giving percentageofcompletion  ,  monthly registration for all months for a given year.
2.  Dynamically adding monthly target for individual agents.

feat:dynamically adding  monthly target for agent

---

server.ts
src/controller/newsController.ts
src/database/migrations/20250814111433-create-news.js
src/database/models/govScheme.ts
src/database/models/news.ts
src/routes/newsRoutes.ts
src/services/newsService.ts
src/validation/govSchemeValidation.ts
src/validation/newsValidation.ts

Design news schema 
Implement news CRUD apis with joi validations
Give related news in news show api
Handle view count for news

feat: Implement news CRUD apis

---

src/services/subAdminService.ts

Add total count in sub admin listing

Add total count in sub admin listing

---

server.ts
src/controller/buyRequestController.ts
src/controller/sellRequestController.ts
src/database/migrations/20250818123440-create-buy-requests.js
src/database/migrations/20250818123503-create-sell-requests.js
src/database/models/buyRequest.ts
src/database/models/sellRequest.ts
src/routes/buyRequestRoutes.ts
src/routes/sellRequestRoutes.ts
src/services/buyRequestService.ts
src/services/sellRequestService.ts
src/utils/generate.ts
src/validation/buyRequestValidation.ts
src/validation/sellRequestValidation.ts

feat: Implement buy and sell request functionality

---

src/controller/eventController.ts
src/database/migrations/20250820071842-changes-in-event-table.js
src/database/migrations/20250820074424-create-event-request-table.js
src/database/models/event.ts
src/database/models/eventRequest.ts
src/routes/eventRoutes.ts
src/services/eventServices.ts
src/services/mandiAgentService.ts
src/utils/constants/permissions.ts
src/validation/eventValidation.ts
src/validation/mandiAgentValidation.ts

user can request to join event ,  super admin will accept/reject the request .
listing of requests .
added isFeatured field in event.

feat: event request implemented

---

src/controller/buyRequestController.ts
src/controller/sellRequestController.ts
src/routes/buyRequestRoutes.ts
src/routes/sellRequestRoutes.ts
src/services/buyRequestService.ts
src/services/sellRequestService.ts

Modify buy/sell listing middleware and searching

Modify buy/sell listing middleware and searching

---

server.ts
src/controller/buyRequestController.ts
src/controller/favRequestController.ts
src/controller/sellRequestController.ts
src/database/migrations/20250821083900-create-favourite-requests.js
src/database/models/buyRequest.ts
src/database/models/favouriteRequest.ts
src/database/models/sellRequest.ts
src/routes/buyRequestRoutes.ts
src/routes/favRequestRoutes.ts
src/routes/sellRequestRoutes.ts
src/services/buyRequestService.ts
src/services/favRequestService.ts
src/services/sellRequestService.ts

Implement favourite functionality for buy and sell requests

feat: Implement favourite functionality for buy and sell requests

---

src/controller/user.ts
src/database/migrations/20250822113901-add-fields-to-user.js
src/database/models/user.ts
src/routes/userRoutes.ts
src/services/agentService.ts
src/services/mandiAgentService.ts
src/services/userServices.ts
src/validation/userValidator.ts

1. update profile and get profile apis for mobile users.
2. given dashboard counts excluded soft deleted users ,  included traders count.
3. added profile picture and bio fields in user.

feat: mobile users profile updation

---

src/services/farmerServices.ts

Add potato sub variety filter in farmer listing

Add potato sub variety filter in farmer listing

---

src/controller/agent.ts
src/database/migrations/20250825063223-add-fields-to-agentMonthlyTarget.js
src/database/models/agentMonthlyTarget.ts
src/services/agentService.ts
src/validation/agentValidation.ts

1. retrieving  agent's performance  user_type wise .
2. adding monthly target user_type wise.

feat: agent performance user type wise

---

src/controller/govSchemeController.ts
src/services/govSchemeService.ts

Add category filter in gov listing

Add category filter in gov listing

---

src/controller/agent.ts
src/controller/farmer.ts
src/controller/traderController.ts
src/services/agentService.ts
src/services/coldStorageService.ts
src/services/farmerServices.ts
src/services/traderService.ts

- Added sorting functionality for trader, farmer, cold storage, and agent listings.  
- Supports sorting by name, createdAt, updatedAt,....

feat: Implement sort by functionality across trader, farmer, cold storage, and agent modules

---

src/validation/coldStorageValidation.ts
src/validation/farmerValidation.ts
src/validation/traderValidation.ts

Add character length validation for fields in Farmer, Trader, and Cold Storage

Add max length validation to Farmer, Trader, and Cold Storage fields

---

src/middlewares/duplicationCheckMiddleware.ts
src/routes/coldStorageRoutes.ts
src/routes/farmerRoutes.ts
src/routes/traderRoutes.ts
src/services/agentService.ts
src/services/coldStorageService.ts

1. created middleware to check for uniqueness in farmer , coldstorage , trader.

fix: uniqueness validation checks implemented

---

src/controller/coldStorage.ts
src/controller/farmer.ts
src/controller/traderController.ts
src/routes/coldStorageRoutes.ts
src/routes/farmerRoutes.ts
src/routes/traderRoutes.ts

Implement mobile update with OTP verification across Farmer, Trader, and ColdStorage modules

feat: Add OTP request and verification flow for updating mobile numbers in Farmer, Trader, and ColdStorage

---

src/database/migrations/20250831082823-change-buy-sell-request-columns.js
src/validation/buyRequestValidation.ts
src/validation/sellRequestValidation.ts

Modify buy and sell request joi validations

fix: Modify buy and sell request validations

---

src/validation/buyRequestValidation.ts
src/validation/sellRequestValidation.ts

Modify joi validation for skin set field

fix: Modify joi validation for skin set field

---

src/validation/newsValidation.ts

removed enum from category in news to allow ai news share  any category.

fix: removed enum from category in news

---

src/controller/farmer.ts
src/controller/traderController.ts
src/controller/user.ts
src/routes/agentRoutes.ts
src/services/subAdminWebService.ts
src/services/userServices.ts
src/utils/commonCode.ts
src/utils/constants/permissions.ts

Modify sub admin permissions
Modify login response

Modify sub admin permissions

---

package.json
src/scripts/updateSubAdminAction.ts

1. seed command to update existing web sub admin permissions.

fix: updated existing web subadmin permission actions

---

src/database/migrations/20250902065451-add-charges-field-to-coldStorage.js
src/database/migrations/20250902103324-create-tables-for-coldstorage.js
src/database/models/coldStorage.ts
src/database/models/monitoringLogger.ts
src/database/models/realTimeAlertSystem.ts
src/services/coldStorageService.ts
src/validation/coldStorageValidation.ts

added gradingCharges , otherCharges ,   loggers , real time alert system type fields   in coldstorage.

feat: added new fields in coldstorage form

---

src/controller/user.ts
src/routes/userRoutes.ts

Allow help & support permissions to sub admin and modify update profile api

Allow help & support permissions to sub admin and modify update profile api

---

src/utils/constants/coldStorageSeedList.ts
src/utils/constants/farmerSeedList.ts
src/utils/constants/traderSeedList.ts

Modify seed data with Hindi, Gujarati and Punjabi languages for farmer, trader and cold storage modules

Modify seed data with Hindi, Gujarati and Punjabi languages

---

src/controller/buyRequestController.ts
src/controller/sellRequestController.ts

Auth check for create buy and sell request for user

Auth check for create buy and sell request for user
